export const EVENT_SEED_DATA = [
  {
    slug: "kajian-tafsir-al-baqarah",
    title: "Kajian Tafsir Al-Quran Surat Al-Baqarah",
    tagline: "Menyelami makna ayat-ayat pilihan Surat Al-Baqarah bersama ustadz berpengalaman.",
    category: "Tafsir",
    imageUrl: "./assets/img/event-1.jpg",
    schedule: "Rabu, 5 November 2025",
    time: "19:00 - 21:00 WIB",
    location: "Masjid Agung Kota",
    address: "Jl. Raya Masjid Agung No. 12, Kota Besar",
    speaker: "Ustadz Ahmad Wijaya",
    amount: 0,
    description:
      "Kajian tematik yang mengupas hikmah dan pesan kehidupan dari ayat-ayat Surat Al-Baqarah. Peserta diajak memahami konteks sejarah, kandungan hukum, dan penerapan praktis dalam keseharian.",
    highlights: [
      "Kupasan tafsir ayat-ayat pilihan Surat Al-Baqarah",
      "Penjelasan hikmah dan penerapan dalam kehidupan modern",
      "Sesi tanya jawab interaktif bersama pemateri",
    ],
    agenda: [
      { time: "18:30", activity: "Registrasi peserta dan tilawah pembuka" },
      { time: "19:00", activity: "Materi utama: Tafsir ayat-ayat tematik" },
      { time: "20:30", activity: "Diskusi dan tanya jawab" },
      { time: "20:55", activity: "Penutup dan doa" },
    ],
    notes: [
      "Silakan membawa mushaf Al-Quran dan alat tulis untuk mencatat.",
      "Materi digital akan dibagikan melalui grup WhatsApp setelah kajian.",
    ],
    preparation: [
      "Datang 15 menit sebelum acara dimulai.",
      "Gunakan pakaian sopan dan menjaga adab majelis ilmu.",
    ],
    contact: {
      wa: "https://wa.me/62811456999",
      phone: "0811-456-999",
      email: "panitia@ketenanganhati.id",
    },
    status: "published",
  },
  {
    slug: "fiqih-muamalat-modern",
    title: "Seminar Fiqih Muamalat dalam Kehidupan Modern",
    tagline: "Memahami hukum transaksi kontemporer agar tetap sesuai tuntunan syariat.",
    category: "Fiqih",
    imageUrl: "./assets/img/event-2.jpg",
    schedule: "Sabtu, 8 November 2025",
    time: "14:00 - 17:00 WIB",
    location: "Gedung Islamic Center",
    address: "Jl. Sudirman No. 45, Gedung Islamic Center Lt. 3",
    speaker: "Ustadz Dr. Muhammad Hasan",
    amount: 50000,
    description:
      "Seminar intensif mengenai fiqih muamalat terkait fintech, marketplace, dan akad-akad yang sering ditemui dalam transaksi harian. Cocok untuk pebisnis muslim dan profesional muda.",
    highlights: [
      "Pembahasan akad murabahah, mudharabah, dan ijarah",
      "Analisis studi kasus transaksi digital",
      "Panduan penyusunan kontrak kerja yang sesuai syariat",
    ],
    agenda: [
      { time: "13:30", activity: "Registrasi dan pembagian materi" },
      { time: "14:00", activity: "Sesi 1: Prinsip umum muamalat" },
      { time: "15:15", activity: "Sesi 2: Studi kasus fintech dan marketplace" },
      { time: "16:30", activity: "Diskusi panel dan konsultasi kasus peserta" },
    ],
    notes: ["Biaya sudah termasuk coffee break dan modul cetak.", "Peserta mendapatkan e-sertifikat."],
    preparation: [
      "Membawa buku catatan atau tablet untuk mencatat poin penting.",
      "Siapkan pertanyaan terkait kasus nyata agar dapat dibahas saat sesi diskusi.",
    ],
    contact: {
      wa: "https://wa.me/628123456780",
      phone: "0812-3456-780",
      email: "muamalat@ketenanganhati.id",
    },
    status: "published",
  },
  {
    slug: "hadits-arbain",
    title: "Kajian Hadits Arbain An-Nawawi",
    tagline: "Menggali 40 hadits pilihan fondasi utama ajaran Islam.",
    category: "Hadits",
    imageUrl: "./assets/img/event-3.jpg",
    schedule: "Rabu, 12 November 2025",
    time: "08:00 - 10:00 WIB",
    location: "Pesantren Dar Al-Hikam",
    address: "Jl. Pesantren No. 9, Kompleks Dar Al-Hikam",
    speaker: "Ustadzah Fatimah Zahra",
    amount: 70000,
    description:
      "Kajian bertahap Hadits Arbain Imam Nawawi dengan penekanan pada pemahaman makna dan implementasinya dalam kehidupan sehari-hari, khususnya bagi keluarga muslim.",
    highlights: [
      "Kupasan sanad dan matan hadits-hadits pilihan",
      "Penerapan nilai hadits dalam kehidupan keluarga",
      "Sesi khusus mentoring muslimah",
    ],
    agenda: [
      { time: "07:30", activity: "Registrasi dan sarapan ringan" },
      { time: "08:00", activity: "Materi utama: hadits-hadits pokok" },
      { time: "09:30", activity: "Diskusi kelompok dan tanya jawab" },
    ],
    notes: ["Peserta mendapatkan booklet ringkasan hadits.", "Disediakan area kids corner bagi ibu yang membawa anak."],
    preparation: ["Membawa mukena untuk shalat dhuha bersama.", "Menggunakan pakaian sopan dan nyaman."],
    contact: {
      wa: "https://wa.me/628234567890",
      phone: "0823-4567-890",
      email: "hadits@ketenanganhati.id",
    },
    status: "published",
  },
  {
    slug: "workshop-tahsin-tajwid",
    title: "Workshop Tahsin dan Tajwid Al-Quran",
    tagline: "Perbaiki makharijul huruf dan tajwid bersama pengajar bersanad.",
    category: "Tahsin",
    imageUrl: "./assets/img/event-4.jpg",
    schedule: "Sabtu, 15 November 2025",
    time: "09:00 - 12:00 WIB",
    location: "Aula Masjid Baiturrohman",
    address: "Jl. Melati No. 5, Komplek Masjid Baiturrohman",
    speaker: "Qori Abdurrahman Al-Hafidz",
    amount: 100000,
    description:
      "Workshop praktik intensif untuk memperbaiki tajwid dan makharijul huruf. Peserta mendapat evaluasi bacaan secara langsung dan target murojaah yang terukur.",
    highlights: [
      "Latihan intensif makharijul huruf",
      "Evaluasi bacaan per peserta",
      "Tips menjaga konsistensi murojaah",
    ],
    agenda: [
      { time: "08:30", activity: "Registrasi dan pemanasan vokal" },
      { time: "09:00", activity: "Sesi 1: teori tahsin praktis" },
      { time: "10:15", activity: "Sesi 2: klinik bacaan per kelompok" },
      { time: "11:30", activity: "Rangkuman dan target murojaah" },
    ],
    notes: ["Kuota terbatas 40 peserta agar latihan lebih efektif.", "Peserta mendapatkan akses rekaman latihan."],
    preparation: [
      "Membawa mushaf pribadi dan alat tulis.",
      "Menjaga kebersihan suara dan menghindari minuman es sebelum acara.",
    ],
    contact: {
      wa: "https://wa.me/628567890123",
      phone: "0856-7890-123",
      email: "tahsin@ketenanganhati.id",
    },
    status: "published",
  },
  {
    slug: "sirah-nabawiyah-mekkah",
    title: "Kajian Sirah Nabawiyah: Periode Mekkah",
    tagline: "Menelusuri strategi dakwah Rasulullah SAW di masa Mekkah.",
    category: "Sirah",
    imageUrl: "./assets/img/event-5.jpg",
    schedule: "Selasa, 18 November 2025",
    time: "19:30 - 21:30 WIB",
    location: "Masjid Al-Ikhlas",
    address: "Jl. Mawar No. 8, Komplek Masjid Al-Ikhlas",
    speaker: "Ustadz Yusuf Abdullah",
    amount: 120000,
    description:
      "Kajian mendalam tentang perjalanan dakwah Rasulullah SAW periode Mekkah, menyoroti strategi, tantangan, dan hikmah yang relevan bagi dakwah masa kini.",
    highlights: [
      "Analisis strategi dakwah Rasulullah SAW di Mekkah",
      "Pelajaran manajemen konflik sosial dari sirah",
      "Refleksi spiritual dan pembinaan karakter",
    ],
    agenda: [
      { time: "19:00", activity: "Registrasi dan tilawah pembuka" },
      { time: "19:30", activity: "Pematerian utama sirah periode Mekkah" },
      { time: "21:00", activity: "Sharing pengalaman dakwah dan penutup" },
    ],
    notes: ["Paket snack hangat tersedia untuk peserta.", "Modul ringkas dikirim melalui email setelah acara."],
    preparation: [
      "Membaca ringkasan sirah sebelum acara (tautan dikirim setelah daftar).",
      "Menjaga ketepatan waktu agar tidak tertinggal materi awal.",
    ],
    contact: {
      wa: "https://wa.me/628678901234",
      phone: "0867-8901-234",
      email: "sirah@ketenanganhati.id",
    },
    status: "published",
  },
  {
    slug: "seminar-parenting-islami",
    title: "Seminar Parenting Islami",
    tagline: "Bangun keluarga sakinah dengan pola asuh bernilai Qurani.",
    category: "Parenting",
    imageUrl: "./assets/img/event-6.jpg",
    schedule: "Kamis, 20 November 2025",
    time: "13:00 - 16:00 WIB",
    location: "Hotel Syariah Grand",
    address: "Jl. Pahlawan No. 88, Ballroom Hotel Syariah Grand",
    speaker: "Ustadz & Ustadzah Family Center",
    amount: 150000,
    description:
      "Seminar interaktif untuk orang tua yang ingin menerapkan pola asuh Islami di tengah tantangan era digital. Dilengkapi simulasi komunikasi dan studi kasus nyata.",
    highlights: [
      "Framework parenting Islami yang aplikatif",
      "Simulasi komunikasi efektif dengan anak",
      "Workbook evaluasi pola asuh",
    ],
    agenda: [
      { time: "12:30", activity: "Registrasi dan makan siang" },
      { time: "13:00", activity: "Sesi 1: Fondasi parenting Islami" },
      { time: "14:30", activity: "Sesi 2: Praktik komunikasi dan studi kasus" },
      { time: "15:30", activity: "Sharing keluarga dan komitmen perubahan" },
    ],
    notes: [
      "Tersedia paket couple (ayah dan ibu) dengan harga spesial.",
      "Disediakan area kids corner berisi aktivitas edukatif.",
    ],
    preparation: ["Membawa notebook dan pena.", "Mengisi pre-test parenting (tautan dikirim via email)."],
    contact: {
      wa: "https://wa.me/628789012345",
      phone: "0878-9012-345",
      email: "parenting@ketenanganhati.id",
    },
    status: "published",
  },
];
